# Imagen base de Python
FROM python:3.8-slim-buster

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Variables de entorno para el despliegue
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Copiar el archivo requirements.txt al contenedor
COPY requirements.txt .

# Instalar las dependencias necesarias
RUN pip3 install --no-cache-dir -r requirements.txt

# Copiar la aplicación al contenedor
COPY app.py .

# Exponer el puerto 5000 (o el puerto que utilice tu aplicación)
EXPOSE 5000

# Comando para ejecutar la aplicación
# CMD ["python3", "app.py"]
CMD ["flask", "run"]